# Generated by Django 5.0.3 on 2024-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.CharField(max_length=200, null=True)),
                ('Protien', models.CharField(max_length=100, null=True)),
                ('Fats', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
